### ISSUE TITLE
disabling onboarding PR, squashing, and signing commits

### ISSUE THREAD

**Issue by adam-moss** [renovateapp/config-help#12]
Hi,

~Can you tell me the config option for disabling an initial onboarding PR?  I've scoured the documentation, and sure I found it, not can't seem to find it again 🤦‍♂️~ `onboarding: false`

Also can you tell me if it is possible for the commits to be squashed when maintaining a `package.json` and a `package-lock.json`?  At the moment it appears that Renovate is creating two separate commits with an identicle commit message.

Finally what would be the equivalent of using the `--signoff` and `--sign` options when doing the `git commit` ?

Thanks

**Comment by rarkins** [comment]
Which platform are you using? GitHub or GitLab?

**Comment by adam-moss** [comment]
I'm using GitLab, the config so far is:

```js
module.exports = {
    autodiscover: true,
    automerge: false,
    commitMessage: '{{semanticPrefix}}Update {{depName}} to {{newVersion}}',
    endpoint: 'https://x.y.z/api/v4',
    onboarding: false,
    platform: 'gitlab',
    prCreation: 'immediate',
    semanticCommits: true,
    timezone: 'Europe/London'
}
```

Initial observations are `autodiscover` setting is being applied, but `onboarding` and `commitMessage` are not.

In terms of how it is being executed within GitLab CI:

```yaml
stages:
    - maintenance

renovate:
    stage: maintenance
    tags: docker
    image: node:alpine
    before_script:
        - npm install -g renovate --production
    script:
        - renovate group/repo
```
